name: ftir-background-subtract
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - wxPython
  - wheel
  - backports       
  - backports.lzma  
  - ca-certificates 
  - certifi         
  - expat           
  - gettext         
  - icu             
  - jpeg            
  - libcxx          
  - libffi          
  - libiconv        
  - libpng          
  - libxml2         
  - llvm-openmp     
  - ncurses         
  - openssl         
  - pip                  
  - readline        
  - setuptools      
  - six             
  - sqlite          
  - tk              
  - wheel           
  - wxpython        
  - xz              
  - zlib            